### ISSUE TITLE
Decide on a suitable AES mode of operation. 

### ISSUE THREAD

**Issue by MonaLindgren** [gitmadnessario/SystemSecurity-DD2497#6]
CBC is vulnerable to the padding oracle attack. We should preferably consult NIST for the recommended AES mode of operation for file encryption. 

In addition, we may want to describe the different modes of operations, the pros and cons and explain the approach we chose, both in the report and at the seminar. This will be a good discussion.

**Comment by gitmadnessario** [comment]
The mode should be XEX as per the feedback we got
